version: '3.1'
services:
  mysql8:
    image: mysql:8
    container_name: mysql8
    restart: always
    env_file: .env
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./mysql:/var/lib/mysql
      - ./log:/var/log/mysql
      - ./etc/mysql/conf.d:/etc/mysql/conf.d
    ports:
      - 13306:3306
    networks:
      - zabbix_network
      - redmine_network

networks:
    zabbix_network:
        external: true
    redmine_network:
        external: true
