services:
  grafana:
    build:
      context: .
    restart: always
    environment:
      GF_ADMIN_PASSWORD: ${GF_ADMIN_PASSWORD}
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - grafana

networks:
  grafana:
    driver: bridge

volumes:
  grafana-storage:
