version: '3.1'
services:
  db:
    image: mysql:5.7
    container_name: wp_db
    restart: always
    env_file: .env
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 3306:3306

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wp
    restart: always
    env_file: .env
    ports:
      - 18080:80
    volumes:
      - ./html:/var/www/html
