- name: apt update
  apt: 
    update_cache: 'yes'

- name: apt upgrade
  apt:
    upgrade: 'yes'

- name: apt-get install modules 1
  apt:
    name:
      - zlib1g-dev
      - gcc
      - make
      - autoconf
      - autogen
      - automake
      - pkg-config
      - uuid-dev

- name: apt-get install modules 2
  apt:
    name:
      - git
      - vim
      - fping
      - mlocate
      - net-tools
      - python3-pip

- name: apt-get install modules 3
  apt:
    name:
      - apache2
      - lm-sensors
      - smokeping
      - netdata

- name: apt-get install modules4
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
