# disk is already connected
- name: copy fstab
  copy:
    src: ../files/etc/fstab
    dest: /etc/fstab

- name: mkdir /mnt/extDisk
  file:
    path: /mnt/extDisk
    state: directory

- name: mount by shell
  shell: 'mount -a'
  args:
    warn: false

- name: mkdir /mnt/extDisk/src
  file:
    path: /mnt/extDisk/src
    state: directory

- name: mkdir /mnt/extDisk/root/workspace
  file:
    path: /mnt/extDisk/root/workspace
    state: directory

- name: mkdir /mnt/extDisk/sho/workspace
  file:
    path: /mnt/extDisk/sho/workspace
    state: directory
    owner: 'sho'
    group: 'sho'
    recurse: true

- name: mdkir /mnt/extDisk/log
  file:
    path: /mnt/extDisk/log
    state: directory
